version: '3.8'

services:
  bot:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # для webhook режима
    env_file: ./src/config/.env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: >
      bash -c "
        if [ $USE_WEBHOOK = 'true' ]; then
          uvicorn src.main:app --host 0.0.0.0 --port 8000;
        else
          python src/main.py;
        fi
      "
    environment:
      USE_WEBHOOK: ${USE_WEBHOOK:-false}

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
